sudo: false
language: php
os:
  - linux
php:
  - 8.0
  - nightly
jobs:
  allow_failures:
  - php: nightly
before_script:
  - phpenv config-rm xdebug.ini; echo "memory_limit=8G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini;
  - pecl install -f mongodb-stable;
  - composer self-update --2
  - COMPOSER_MEMORY_LIMIT=5G composer install --prefer-dist
script: composer run-script test
notifications:
  email: false
branches:
  only:
  - main
